# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-22 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
('ab_scheduler', '0007_auto_20190811_2044'),
       ('abmetrics_django', '0003_auto_20190529_1457')
]
    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('obj_type', models.CharField(choices=[(b'MetricGroup', b'MetricGroup'), (b'MetricVariable', b'MetricVariable'), (b'ListenerSummary', b'ListenerSummary'), (b'Experiment', b'Experiment'), (b'CrossSegmentCount', b'CrossSegmentCount'), (b'Job', b'Job'), (b'Baseline', b'Baseline'), (b'BaselineInit', b'BaselineInit'), (b'ExposureRollup', b'ExposureRollup'), (b'BaselineDenormalizer', b'BaselineDenormalizer'), (b'HiveListenerSummary', b'HiveListenerSummary'), (b'Metric', b'Metric')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete'), ('Waiting for Dependencies', 'Waiting for Dependencies'), ('Failed', 'Failed')], max_length=100, null=True)),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('upstream_dep', models.ManyToManyField(related_name='downstream', to='ab_scheduler.Dependency')),
            ],
        ),
    ]
